#!/usr/bin/env bash
set -eux

# Install jupyter_lsp python package
python -m pip install jupyter_lsp
jupyter serverextension enable --sys-prefix --py jupyter_lsp

# Install jupyterlab-lsp and debugger jupyterlab extensions
jupyter labextension install @krassowski/jupyterlab-lsp install @jupyterlab/debugger@0.2.0 --debug

# Uninstall ipykernel
pip uninstall -y ipykernel

curl -o index.ipynb https://raw.githubusercontent.com/krassowski/jupyterlab-lsp/a39e3f7f87cec3d156fddca554ab5356840dd485/examples/Python.ipynb

# Update the python notebook to use xpython
python binder/update_python_example.py
